image:
  file: .gitpod.dockerfile
tasks:
 - init: . ${GITPOD_REPO_ROOT}/.theia/init_tasks.sh    
   command: >
     npm install -g sass
     sass --watch assets/scss:assets/css
     python3 -m "http.server"
vscode:
  extensions:
    - ms-python.python@2019.8.30787:TnGEOx35GXMhyKLjDGz9Aw==
    - formulahendry.auto-close-tag@0.5.9:JZIefALANqOfhSK1TU4+Fw==
    - mkaufman.HTMLHint@0.10.0:xevX4CvYOkKd8xjvtJQiGQ==
    - eventyret.bootstrap-4-cdn-snippet@1.9.0:I8wcXFcKWQIROg7J0SLLqg==
    - esbenp.prettier-vscode@5.7.1:4Zx39KyQMoIz7x94PSmDmQ==
    - kevinglasson.cornflakes-linter@0.5.1:KAaMshgHOKan8eojXQ53OQ==
    - ritwickdey.live-sass@3.0.0:x2c+sCJm+QmH2qn2h1X9Zw==